ALTER TABLE bsc ADD COLUMN IF NOT EXISTS dia_semana text;
ALTER TABLE bsc ADD COLUMN IF NOT EXISTS regional text;
ALTER TABLE bsc ADD COLUMN IF NOT EXISTS supervisor text;
ALTER TABLE bsc ADD COLUMN IF NOT EXISTS motorista text;
ALTER TABLE bsc ADD COLUMN IF NOT EXISTS id_rota text;
ALTER TABLE bsc ADD COLUMN IF NOT EXISTS saldo numeric DEFAULT 0;
ALTER TABLE bsc ADD COLUMN IF NOT EXISTS entregues numeric DEFAULT 0;
ALTER TABLE bsc ADD COLUMN IF NOT EXISTS "insucessosDetalhados" jsonb;
